export type Department = {
  slug: string;
  name: string;
  icon: string;
  floor: string;
  summary: string;
  treats: string[];
  goInPerson: string[];
  online: string;
  expect: string[];
  bring: string[];
  free: string[];
  topics: string[];
};

export const departments: Department[] = [
  {
    slug: "emergency",
    name: "Emergency",
    icon: "🚑",
    floor: "Ground floor · Open 24 hours",
    summary: "For life-threatening problems that need help immediately.",
    treats: [
      "Chest pain, stroke signs, and severe breathing difficulty",
      "Serious injuries, accidents, burns, and heavy bleeding",
      "Fits, fainting, or a person who cannot be woken",
      "Poisoning, overdose, and snake bites",
      "Pregnancy emergencies",
    ],
    goInPerson: ["Always. Call 108 for a free ambulance, or go to the nearest hospital emergency now."],
    online: "Not suitable. Emergencies need in-person care immediately.",
    expect: [
      "A nurse checks how serious your condition is (triage). The most serious patients are seen first.",
      "A doctor examines you and may order urgent tests.",
      "You may be treated and sent home, admitted, or referred to a bigger hospital.",
    ],
    bring: ["The patient's ID and any health card", "A list of medicines they take", "Any medicine or poison container involved"],
    free: ["108 ambulance service is free", "Emergency care in government hospitals"],
    topics: ["/heart"],
  },
  {
    slug: "general-medicine",
    name: "General OPD",
    icon: "🩺",
    floor: "Ground floor · Outpatient Department",
    summary: "The first stop for most health problems in adults.",
    treats: [
      "Fever, cough, cold, and infections",
      "Stomach problems, vomiting, and diarrhoea",
      "Headaches, body aches, and tiredness",
      "Skin problems and urine problems",
      "Diabetes and high blood pressure check-ups",
    ],
    goInPerson: ["Fever that needs a malaria or dengue test", "Problems that need an examination or blood test"],
    online: "Good for follow-ups, ongoing conditions, and advice on mild problems through eSanjeevani.",
    expect: [
      "Register at the OPD counter and get an OPD slip.",
      "Wait for your turn, then the doctor asks about your problem and examines you.",
      "You may be sent for tests or given a prescription, and told when to come back.",
    ],
    bring: ["ID card (Aadhaar or other)", "Old prescriptions and test reports", "List of medicines you take", "Your visit summary from the Triage Desk"],
    free: ["OPD consultation in government hospitals", "Free blood sugar and blood pressure checks for adults over 30", "Free malaria test at health centres and from ASHAs"],
    topics: ["/diabetes", "/malaria"],
  },
  {
    slug: "child-health",
    name: "Child Health",
    icon: "🧒",
    floor: "First floor · Paediatrics",
    summary: "Care for babies, children, and teenagers.",
    treats: [
      "Fever, cough, and breathing problems in children",
      "Diarrhoea and dehydration",
      "Newborn care and feeding problems",
      "Growth and nutrition concerns",
      "Vaccinations",
    ],
    goInPerson: ["Any illness in a baby under 3 months", "A child who is not feeding, very sleepy, or breathing fast", "Vaccinations"],
    online: "Can help with advice on mild illness and feeding questions, but sick babies should be seen in person.",
    expect: [
      "The child is weighed and checked for fever and breathing.",
      "The doctor asks about the illness, feeding, and vaccinations.",
      "Very sick children may be admitted for care.",
    ],
    bring: ["Child's vaccination card / Mother and Child Protection (MCP) card", "Birth certificate or ID if available", "Any medicines the child has been given"],
    free: ["All vaccines under the Universal Immunization Programme", "Free treatment for sick newborns under JSSK"],
    topics: ["/mother-child"],
  },
  {
    slug: "maternity",
    name: "Maternity",
    icon: "🤱",
    floor: "First floor · Obstetrics & Gynaecology",
    summary: "Pregnancy check-ups, safe delivery, and women's health.",
    treats: [
      "Pregnancy check-ups and scans",
      "Labour and delivery",
      "Problems during and after pregnancy",
      "Family planning",
      "Women's health problems such as abnormal bleeding",
    ],
    goInPerson: ["Pregnancy check-ups (at least 4)", "Delivery — plan to give birth in a hospital", "Any danger sign in pregnancy — go immediately"],
    online: "Good for questions about family planning and minor concerns between check-ups.",
    expect: [
      "Your weight, blood pressure, and baby's growth are checked.",
      "Blood and urine tests, and scans when needed.",
      "You get iron and folic acid tablets and a plan for a safe delivery.",
    ],
    bring: ["Mother and Child Protection (MCP) card", "ID card", "Previous test and scan reports"],
    free: ["Free delivery, medicines, tests, food, and transport under JSSK", "Free pregnancy check-ups at government facilities"],
    topics: ["/mother-child"],
  },
  {
    slug: "cancer-care",
    name: "Cancer Care",
    icon: "🎗️",
    floor: "Second floor · Oncology",
    summary: "Screening, diagnosis, and treatment of cancer.",
    treats: [
      "Screening for mouth, breast, and cervical cancer",
      "Checking lumps, non-healing ulcers, and unusual bleeding",
      "Cancer treatment and follow-up",
      "Pain relief and palliative care",
    ],
    goInPerson: ["Any warning sign lasting more than 2–3 weeks", "Screening if you are over 30"],
    online: "eSanjeevani can advise whether you need to be seen, but cancer checks need an in-person examination.",
    expect: [
      "The doctor asks about your symptoms and habits like tobacco and kuhva.",
      "You may need an examination, scan, or biopsy (a small tissue sample).",
      "If cancer is found, a team plans your treatment.",
    ],
    bring: ["ID card and any health insurance or PM-JAY card", "All previous reports and scans", "List of medicines"],
    free: ["Free screening for common cancers for adults over 30", "Ayushman Bharat PM-JAY can cover cancer treatment for eligible families"],
    topics: ["/cancer", "/tobacco"],
  },
  {
    slug: "heart-care",
    name: "Heart Care",
    icon: "❤️",
    floor: "Second floor · Cardiology",
    summary: "Heart disease, high blood pressure, and stroke prevention.",
    treats: ["High blood pressure", "Chest pain and heart disease", "Irregular heartbeat", "Heart failure and swelling with breathlessness"],
    goInPerson: ["Chest discomfort during activity", "Very high blood pressure readings", "Chest pain right now — go to Emergency instead"],
    online: "Good for follow-up of blood pressure and medicine questions.",
    expect: ["Blood pressure check and examination.", "Tests such as ECG and blood tests.", "Advice on medicines, food, and activity."],
    bring: ["Your blood pressure readings if you have them", "Old ECG and test reports", "List of medicines"],
    free: ["Free blood pressure checks for adults over 30 at government health centres"],
    topics: ["/heart", "/diabetes"],
  },
  {
    slug: "chest-tb",
    name: "Chest & TB",
    icon: "🫁",
    floor: "Third floor · Pulmonology",
    summary: "Lung problems, long-lasting cough, and TB.",
    treats: ["Cough lasting more than 2 weeks", "Tuberculosis (TB)", "Asthma and breathing problems", "Lung damage from smoking"],
    goInPerson: ["Cough for more than 2 weeks — get a free TB test", "Coughing up blood", "Breathlessness that is getting worse"],
    online: "Good for advice and follow-up during TB treatment.",
    expect: ["You may be asked to give a phlegm (sputum) sample.", "A chest X-ray may be done.", "If you have TB, free treatment starts and a health worker supports you."],
    bring: ["ID card", "Old chest X-rays and reports"],
    free: ["Free TB tests and medicines", "Nutrition support for TB patients under the National TB Elimination Programme"],
    topics: ["/tb", "/tobacco"],
  },
  {
    slug: "mental-health",
    name: "Mental Health & De-addiction",
    icon: "🧠",
    floor: "Third floor · Psychiatry",
    summary: "Support for stress, depression, anxiety, and alcohol or drug problems.",
    treats: ["Depression and anxiety", "Sleep problems", "Alcohol and drug dependence", "Stress after difficult life events"],
    goInPerson: ["Thoughts of self-harm — call 14416 or 112 now", "Unable to look after yourself", "Withdrawal from alcohol or drugs"],
    online: "Tele-MANAS (14416) and eSanjeevani are good first steps. Talking support works well by phone and video.",
    expect: ["A doctor or counsellor talks with you privately.", "Together you make a plan — counselling, medicine, or both.", "Your information is confidential."],
    bring: ["List of medicines", "A family member or friend for support, if you wish"],
    free: ["Tele-MANAS: free 24-hour mental health support on 14416", "Mental health care at government hospitals"],
    topics: ["/mental", "/drugs"],
  },
  {
    slug: "dental-mouth",
    name: "Dental & Mouth",
    icon: "🦷",
    floor: "Ground floor · Dental OPD",
    summary: "Teeth, gums, and early detection of mouth cancer.",
    treats: ["Toothache and gum problems", "Mouth ulcers and white or red patches", "Difficulty opening the mouth", "Mouth checks for tobacco and kuhva users"],
    goInPerson: ["A mouth ulcer or patch lasting more than 2 weeks", "Swelling of the face from a tooth"],
    online: "Can advise on mild problems, but mouth checks need an in-person examination.",
    expect: ["The dentist examines your teeth, gums, and the inside of your mouth.", "Suspicious patches may be referred to Cancer Care."],
    bring: ["ID card", "List of medicines"],
    free: ["Oral cancer screening for adults over 30 at government health centres"],
    topics: ["/tobacco", "/cancer"],
  },
  {
    slug: "infectious-diseases",
    name: "HIV & Infections (ICTC)",
    icon: "🛡️",
    floor: "Ground floor · Integrated Counselling & Testing Centre",
    summary: "Confidential HIV testing and care for infections.",
    treats: ["HIV testing and counselling", "HIV treatment (ART)", "Sexually transmitted infections", "Hepatitis B and C"],
    goInPerson: ["Possible exposure to HIV in the last 72 hours — go now and ask about PEP", "HIV testing"],
    online: "The AIDS Helpline (1097) gives free, confidential information.",
    expect: ["A counsellor talks with you privately before and after the test.", "The test is quick, and the result is confidential.", "If positive, you are linked to free treatment."],
    bring: ["ID card if available — testing is confidential"],
    free: ["Free HIV testing, counselling, and lifelong ART treatment", "Free condoms at government health centres"],
    topics: ["/hiv", "/drugs"],
  },
];

export const departmentBySlug = (slug: string) => departments.find((d) => d.slug === slug);
