export const healthTopics = [
  {
    href: "/cancer",
    keywords: "tumour tumor lump oral mouth screening",
    icon: "🎗️",
    title: "Cancer Awareness",
    text: "Learn early warning signs, risk factors, and when to seek help.",
  },
  {
    href: "/tobacco",
    keywords: "kuhva betel paan smoking cigarette bidi gutkha khaini quit oral mouth",
    icon: "🚭",
    title: "Tobacco & Oral Health",
    text: "Understand how smoking, tobacco, and betel nut can affect health.",
  },
  {
    href: "/diabetes",
    keywords: "sugar blood glucose",
    icon: "🩸",
    title: "Diabetes Awareness",
    text: "Simple information on sugar level, diet, exercise, and regular check-up.",
  },
  {
    href: "/heart",
    keywords: "bp blood pressure hypertension chest pain cholesterol",
    icon: "❤️",
    title: "Heart Health",
    text: "Know the basics of blood pressure, chest pain, and healthy habits.",
  },
  {
    href: "/mental",
    keywords: "depression stress anxiety sleep suicide addiction drugs alcohol counselling",
    icon: "🧠",
    title: "Mental Wellbeing",
    text: "Simple guidance on stress, sleep, addiction, and asking for support.",
  },
  {
    href: "/hiv",
    keywords: "aids hiv test ictc art condom needle sexually transmitted std sti pep",
    icon: "🛡️",
    title: "HIV & AIDS",
    text: "How HIV spreads, how it does not, and where to get a free, confidential test.",
  },
  {
    href: "/tb",
    keywords: "tb tuberculosis cough phlegm lungs night sweats",
    icon: "🫁",
    title: "Tuberculosis (TB)",
    text: "A cough lasting more than 2 weeks should be tested. TB is curable and treatment is free.",
  },
  {
    href: "/malaria",
    keywords: "malaria dengue mosquito fever net chills",
    icon: "🦟",
    title: "Malaria & Dengue",
    text: "Warning signs of mosquito-borne fevers, and how to protect your family.",
  },
  {
    href: "/drugs",
    keywords: "alcohol drugs heroin addiction overdose injecting de-addiction zu",
    icon: "🚫",
    title: "Alcohol & Drug Use",
    text: "Signs of addiction, how to help someone, and what to do in an overdose.",
  },
  {
    href: "/mother-child",
    keywords: "pregnancy pregnant baby newborn breastfeeding vaccine vaccination delivery child immunisation",
    icon: "🤱",
    title: "Mother & Child Health",
    text: "Danger signs in pregnancy and newborns, check-ups, breastfeeding, and vaccines.",
  },
];
