// Writes docs/quality/CONVERSATION_ACCURACY.md from the accuracy harness.
//   npm run quality:report
import { writeFileSync } from "node:fs";
import { HELD_OUT_A, HELD_OUT_B, PHRASES, measure } from "../tests/safety/accuracy";
import { play } from "../tests/safety/fidelity";

const N = 400;
const sets = [
  ["Training phrasings", "Used to build the vocabulary.", PHRASES],
  ["Held-out set A", "First measured untuned (85.7% understood, 0 unsafe, 9 wrong); then tuned against.", HELD_OUT_A],
  ["Held-out set B", "Never tuned against, except one safety fix (see history). **The honest estimate.**", HELD_OUT_B],
] as const;

const pct = (a: number, b: number) => (b ? `${((100 * a) / b).toFixed(1)}%` : "—");
let md = `# Conversation accuracy — does the doctor record what the patient meant?

Generated by \`npm run quality:report\` (method: \`tests/safety/accuracy.ts\`;
floors enforced by \`tests/safety/accuracy.test.ts\`). Do not edit by hand.

${N} seeded simulated patients per set. Each knows its intended answer and says
it in words; the recorded value is compared with the intent.

- **Understood** — recorded exactly what was meant.
- **Asked again** — not understood; the doctor asked another way (then the patient tapped the answer). A cost, not a danger.
- **Wrong** — recorded something the patient did not mean.
- **Unsafe** — a "yes" or "not sure" to a danger-sign question recorded as "no".

| Set | About | Answers | Understood | Asked again | Wrong | Unsafe |
| --- | --- | ---: | ---: | ---: | ---: | ---: |
`;
const details: string[] = [];
for (const [name, about, phrases] of sets) {
  const t = measure(N, phrases);
  const n = t.correct + t.again + t.wrong;
  md += `| ${name} | ${about} | ${n} | ${pct(t.correct, n)} | ${pct(t.again, n)} | ${t.wrong} | ${t.unsafe} |\n`;
  let d = `### ${name}\n\n| Step | Answers | Understood | Asked again | Wrong |\n| --- | ---: | ---: | ---: | ---: |\n`;
  for (const [step, v] of Object.entries(t.byStep)) d += `| ${step} | ${v.n} | ${pct(v.correct, v.n)} | ${pct(v.again, v.n)} | ${v.wrong} |\n`;
  const missed = Object.entries(t.missed).sort((a, b) => b[1] - a[1]).slice(0, 12);
  if (missed.length) d += `\nMost often not understood: ${missed.map(([k]) => k.replace(/^[^:]+: /, "")).join(", ")}.\n`;
  details.push(d);
}
md += `
## By step

${details.join("\n")}
## Summary fidelity after messy visits

\${FIDELITY}

## History — what this harness found

| Found by | Problem | Effect | Fix |
| --- | --- | --- | --- |
| Training set | "I'm not certain" recorded as **No** | 21 unsafe danger-sign recordings in 400 visits | Uncertainty words checked before negation |
| Training set | "I think so" recorded as Not sure | A probable yes to a danger sign got "urgent" instead of "emergency" | Hedged yes is yes (errs toward care) |
| Training set | "more than two weeks" → 4 days to 2 weeks | Wrong duration (a TB-relevant cut-off) | "more than / less than" shift the boundary |
| Held-out A | "not improving or worse" → Getting better | Wrong course of illness | Negated change is not a direction; "not getting better" is asked |
| Held-out B | "I didn't check" recorded as **No** | 17 unsafe danger-sign recordings | Not checked / can't remember → Not sure |
| Fidelity | "Sorry, I meant no" taken as the answer to the **next** question; the wrong answer stayed | 83 in 600 visits; denied symptoms listed as present; a corrected "yes" to a danger sign stayed "no" | Clear corrections change the last answer and say so; an ambiguous "actually no…" is asked about; a correction to "yes" is re-checked for an emergency |

## Limits

- English phrasings written by the development team, not collected from
  patients. Real Mizoram phrasing (Mizo, Mizo-English) is **not** covered and
  needs a reviewed phrase list from qualified translators.
- When set B is tuned against, record its score here, rename it, and write a
  new held-out set — ideally from real phrasings collected with consent in a pilot.
- Speech recognition errors are not modelled here (see the speech-confirmation step).
`;
const visits = 1500;
const findings = Array.from({ length: visits }, (_, i) => play(i + 1)).flat();
md = md.replace(
  "${FIDELITY}",
  `${visits} seeded visits (\`tests/safety/fidelity.ts\`). Each patient has a hidden truth and sometimes answers wrongly then corrects themselves in words ("sorry, I meant yes", "actually it started last week"), says "I don't know", asks why or what a word means, or mentions a second problem. Every summary row is then compared with the truth.\n\n**Mismatches: ${findings.length}.**${findings.length ? "\n\n" + findings.slice(0, 10).map((f) => `- seed ${f.seed}: ${f.problem}`).join("\n") : ""}`,
);
writeFileSync("docs/quality/CONVERSATION_ACCURACY.md", md);
console.log("Wrote docs/quality/CONVERSATION_ACCURACY.md");
